# Site settings
title: Austin Wu
email:
description: >- # this means to ignore newlines until "baseurl:"
  Cornell 2027. Applied and Engineering Physics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://austin-wu.com" # the base hostname & protocol for your site
twitter_username: AustinWu_
github_username: Austin4705
google_analytics: G-HNG7S83RPV

logo: "assets/pfp.jpeg"
social:
  name: Austin Wu
  links:
    - https://github.com/Austin4705
    - https://www.instagram.com/austin._.wu/
    - https://www.linkedin.com/in/austin--wu/
    - https://x.com/AustinWu_
    - https://calendly.com/austin4705/scheduler

# Collections
collections:
  notes:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: "private/**"
    values:
      sitemap: false
  - scope:
      path: "assets/private/**"
    values:
      sitemap: false

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sitemap settings
sitemap:
  exclude:
    - "/private/"
    - "/private/**"
    - "/files/private/"
    - "/files/private/**"

permalink: /blog/:categories/:year/:month/:day/:title:output_ext

header_pages:
  - blog.md
  - notes.md
  - resume.md
  - projects.md
  - publications.md

# Include PDFs from collections and posts
include:
  - _notes/*.pdf
  - _notes/*.md
  - _posts/*.pdf
  - "*.pdf"
  - "**/*.pdf"

# Keep files in output
keep_files:
  - "*.pdf"
  - "notes/*.pdf"
  - "private/**/*.pdf"

# Exclude from processing
exclude:
  - "*.aux"
  - "*.log"
  - "*.out"
  - "*.synctex.gz"
  - "*.fls"
  - "*.fdb_latexmk"
  - "Gemfile"
  - "Gemfile.lock"
  - "_posts/*.tex"

# Markdown Processing
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

