# Site settings
title: Wu, V, Z & Co.
email:
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://austin-wu.com/FundWebsite" # the base hostname & protocol for your site #TODO:
google_analytics: G-HNG7S83RPV #TODO:

logo: "assets/logo.jpeg"
social:
  name:

# Collections
collections:
  notes:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: "private/**"
    values:
      sitemap: false
  - scope:
      path: "assets/private/**"
    values:
      sitemap: false

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sitemap settings
sitemap:
  exclude:
    - "/private/"
    - "/private/**"
    - "/files/private/"
    - "/files/private/**"

permalink: /updates/:categories/:year/:month/:day/:title:output_ext

header_pages:
  - investments.md

# Include PDFs from collections and posts
include:
  - _notes/*.pdf
  - _notes/*.md
  - _posts/*.pdf
  - "*.pdf"
  - "**/*.pdf"

# Keep files in output
keep_files:
  - "*.pdf"
  - "notes/*.pdf"
  - "private/**/*.pdf"

# Exclude from processing
exclude:
  - "*.aux"
  - "*.log"
  - "*.out"
  - "*.synctex.gz"
  - "*.fls"
  - "*.fdb_latexmk"
  - "Gemfile"
  - "Gemfile.lock"
  - "_posts/*.tex"

# Markdown Processing
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
